
name: Go
on: 
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Get version
              id: versioning
              uses: flynshue/version-action@v0.0.1
            - name: Set up Go 1.21.6
              uses: actions/setup-go@v4
              with:
                  go-version: 1.21.6
            - name: Install dependencies and build
              uses: addnab/docker-run-action@v3
              with:
                image: alpine:3.19
                run: |
                      apk add --no-cache curl
                      curl -LO https://golang.org/dl/go1.21.6.linux-amd64.tar.gz
                      tar -C /usr/local -xzf go1.21.6.linux-amd64.tar.gz
                      export PATH=$PATH:/usr/local/go/bin
                      go get
                      go build -v -o ./bin/
            - name: Release
              id: release
              uses: softprops/action-gh-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  files: |
                          bin/*
                  tag_name: ${{ steps.versioning.outputs.version }}
                  name: Release ${{ github.event.head_commit.message }}
                  body: |
                         Release ${{ github.ref }}